version: '3'
services:
  postgresql:
    image: postgres:10.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: phoenix_elm_websocket_boilerplate_dev
    volumes:
     - ${PWD}/data/docker/postgres:/var/lib/postgresql/data

